### ISSUE TITLE
Error in baz_swig import 

### ISSUE THREAD

**Issue by sprakashb** [balint256/gr-baz#41]
Trying HDSDR on linux (Ubuntu 15.10) as given in 
https://www.reddit.com/r/RTLSDR/comments/2e58bz/install_script_for_hdsdr_on_linux/
when running      python2 borip_server.py 
getting the following error.  Somewhere baz_swig seems missing. Any help?
(I am novice in Python)
Traceback (most recent call last):
  File "borip_server.py", line 3, in <module>
    from baz import borip_server
  File "/usr/local/lib/python2.7/dist-packages/baz/__init__.py", line 40, in <module>
    from baz_swig import *
ImportError: No module named baz_swig

**Comment by robellebor** [comment]
hello.... did u fix ur problem .... coz am having the same problem now ... and i need ur help if u ....

**Comment by jerrydark** [comment]
I also have same problem except it says:

**Comment by XgDuan** [comment]
I also have the same problem that it says:
No module named baz_swig.
I search this problem in the issue list and found this open issue. 
I also found the solution towards this problem. The key point is that you should ensure swig is installed in your machine. If not, uninstall gr_baz and install swig first.
@jerrydark @robellebor @sprakashb

**Comment by jerrydark** [comment]
I confirm this solution.
